# HRM model and training configuration

# model parameters
model:
  num_colors: 10
  d_model: 128
  d_l: 160
  d_h: 192
  max_len: 900  # 30x30

# training parameters
training:
  batch_size: 32
  lr: 3e-3
  weight_decay: 1e-4
  grad_clip: 1.0
  epochs: 100
  warmup_steps: 200
  
# HRM parameters
hrm:
  cycles: 4
  inner_steps: 3
  one_step_grad: true
  
# loss parameters
loss:
  ds_weight: 1.0
  ds_decay: 0.0
  act_weight: 0.05
  
# data parameters
data:
  target_size: 30
  val_ratio: 0.2
  k_support: 3  # number of support examples per task 